### ISSUE TITLE
mockc CLI  error: destination file should go file: _

### ISSUE THREAD

**Issue by holyachon** [KimMachineGun/mockc#1]
### command
`mockc -name=DynamoDBMock -destination=pkg/repositories/dynamoaa.go github.com/aws/aws-sdk-go/service/dynamodb/dynamodbiface.DynamoDBAPI `

### error message
```
destination file should be go file: _
```

**Comment by KimMachineGun** [comment]
Thank you for reporting it.
It was fixed at https://github.com/KimMachineGun/mockc/releases/tag/v1.3.2.
Please bump to v1.3.2.
